# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0002_auto_20180105_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField()),
                ('privacy', models.IntegerField(max_length=1)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('toughness', models.IntegerField(max_length=1)),
                ('time', models.IntegerField(max_length=1)),
                ('cost', models.IntegerField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='users_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='idea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='activities_app.Idea'),
        ),
    ]
