# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-06 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0002_auto_20180106_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(),
        ),
    ]
