# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-15 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0004_auto_20180106_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='idea',
        ),
        migrations.AddField(
            model_name='activity',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='toughness',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='privacy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='idea',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='idea',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='idea',
            name='toughness',
            field=models.IntegerField(),
        ),
    ]
