# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-15 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0006_activity_idea_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
