# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-15 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0007_idea_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
